import {
  AppWindow,
  BarChart3,
  Binary,
  Blocks,
  BookOpen,
  Bot,
  Boxes,
  Braces,
  Building2,
  Cable,
  Cloud,
  CloudCog,
  Component,
  Contact,
  CreditCard,
  Cpu,
  Database,
  FileCode,
  FileJson,
  Flame,
  Frame,
  Gauge,
  GitBranch,
  Globe,
  Hexagon,
  KeyRound,
  LayoutDashboard,
  Layers,
  Lock,
  Megaphone,
  MessageSquare,
  MousePointerClick,
  PanelTop,
  PenTool,
  Plug,
  Repeat,
  Search,
  Server,
  Settings2,
  Share2,
  Shield,
  ShieldAlert,
  Smartphone,
  Sparkles,
  Tablet,
  Triangle,
  TrendingUp,
  Users,
  Webhook,
  Wind,
  Workflow,
  Zap,
  type LucideIcon,
} from "lucide-react";

import type { TechnologyClusterId } from "@/types";

export const clusterIcons: Record<TechnologyClusterId, LucideIcon> = {
  frontend: AppWindow,
  mobile: Smartphone,
  backend: Server,
  ai: Sparkles,
  database: Database,
  cloud: Cloud,
  devops: GitBranch,
  design: PenTool,
  enterprise: Building2,
  integrations: Cable,
  security: Shield,
  marketing: TrendingUp,
};

const techIcons: Record<string, LucideIcon> = {
  react: Component,
  nextjs: Triangle,
  vue: Layers,
  typescript: FileCode,
  javascript: FileJson,
  tailwind: Wind,
  flutter: Tablet,
  "react-native": Smartphone,
  expo: AppWindow,
  android: Cpu,
  ios: Tablet,
  nodejs: Server,
  python: Braces,
  laravel: Boxes,
  php: FileCode,
  fastapi: Zap,
  graphql: Share2,
  rest: Globe,
  openai: Sparkles,
  claude: MessageSquare,
  gemini: Sparkles,
  llms: Bot,
  rag: BookOpen,
  "ai-agents": Bot,
  mcp: Plug,
  postgresql: Database,
  mysql: Database,
  mongodb: Binary,
  redis: Zap,
  prisma: Boxes,
  firebase: Flame,
  aws: Cloud,
  vercel: Triangle,
  cloudflare: Globe,
  "google-cloud": CloudCog,
  azure: CloudCog,
  serverless: Workflow,
  docker: Boxes,
  kubernetes: Hexagon,
  git: GitBranch,
  "github-actions": Workflow,
  cicd: Repeat,
  terraform: Blocks,
  figma: PenTool,
  "design-systems": LayoutDashboard,
  prototyping: MousePointerClick,
  wireframing: Frame,
  ux: Users,
  erp: Building2,
  crm: Contact,
  saas: PanelTop,
  dashboards: LayoutDashboard,
  portals: PanelTop,
  "admin-panels": Settings2,
  "api-integration": Cable,
  "payment-gateways": CreditCard,
  webhooks: Webhook,
  "workflow-automation": Workflow,
  "ai-automation": Sparkles,
  authentication: KeyRound,
  "api-security": Shield,
  owasp: ShieldAlert,
  "data-protection": Lock,
  performance: Gauge,
  seo: Search,
  "ai-seo": Sparkles,
  "paid-ads": Megaphone,
  "social-media": Share2,
  analytics: BarChart3,
  cro: TrendingUp,
};

export function getTechIcon(slug: string): LucideIcon {
  return techIcons[slug] ?? Boxes;
}
